/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SourcingRouteImport } from './routes/sourcing'
import { Route as RapportRouteImport } from './routes/rapport'
import { Route as ProspectsRouteImport } from './routes/prospects'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as PartageRouteImport } from './routes/partage'
import { Route as FacturationRouteImport } from './routes/facturation'
import { Route as ChasseRouteImport } from './routes/chasse'
import { Route as AnalyseRouteImport } from './routes/analyse'
import { Route as IndexRouteImport } from './routes/index'

const SourcingRoute = SourcingRouteImport.update({
  id: '/sourcing',
  path: '/sourcing',
  getParentRoute: () => rootRouteImport,
} as any)
const RapportRoute = RapportRouteImport.update({
  id: '/rapport',
  path: '/rapport',
  getParentRoute: () => rootRouteImport,
} as any)
const ProspectsRoute = ProspectsRouteImport.update({
  id: '/prospects',
  path: '/prospects',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const PartageRoute = PartageRouteImport.update({
  id: '/partage',
  path: '/partage',
  getParentRoute: () => rootRouteImport,
} as any)
const FacturationRoute = FacturationRouteImport.update({
  id: '/facturation',
  path: '/facturation',
  getParentRoute: () => rootRouteImport,
} as any)
const ChasseRoute = ChasseRouteImport.update({
  id: '/chasse',
  path: '/chasse',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyseRoute = AnalyseRouteImport.update({
  id: '/analyse',
  path: '/analyse',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyse': typeof AnalyseRoute
  '/chasse': typeof ChasseRoute
  '/facturation': typeof FacturationRoute
  '/partage': typeof PartageRoute
  '/pipeline': typeof PipelineRoute
  '/prospects': typeof ProspectsRoute
  '/rapport': typeof RapportRoute
  '/sourcing': typeof SourcingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyse': typeof AnalyseRoute
  '/chasse': typeof ChasseRoute
  '/facturation': typeof FacturationRoute
  '/partage': typeof PartageRoute
  '/pipeline': typeof PipelineRoute
  '/prospects': typeof ProspectsRoute
  '/rapport': typeof RapportRoute
  '/sourcing': typeof SourcingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyse': typeof AnalyseRoute
  '/chasse': typeof ChasseRoute
  '/facturation': typeof FacturationRoute
  '/partage': typeof PartageRoute
  '/pipeline': typeof PipelineRoute
  '/prospects': typeof ProspectsRoute
  '/rapport': typeof RapportRoute
  '/sourcing': typeof SourcingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyse'
    | '/chasse'
    | '/facturation'
    | '/partage'
    | '/pipeline'
    | '/prospects'
    | '/rapport'
    | '/sourcing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyse'
    | '/chasse'
    | '/facturation'
    | '/partage'
    | '/pipeline'
    | '/prospects'
    | '/rapport'
    | '/sourcing'
  id:
    | '__root__'
    | '/'
    | '/analyse'
    | '/chasse'
    | '/facturation'
    | '/partage'
    | '/pipeline'
    | '/prospects'
    | '/rapport'
    | '/sourcing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyseRoute: typeof AnalyseRoute
  ChasseRoute: typeof ChasseRoute
  FacturationRoute: typeof FacturationRoute
  PartageRoute: typeof PartageRoute
  PipelineRoute: typeof PipelineRoute
  ProspectsRoute: typeof ProspectsRoute
  RapportRoute: typeof RapportRoute
  SourcingRoute: typeof SourcingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sourcing': {
      id: '/sourcing'
      path: '/sourcing'
      fullPath: '/sourcing'
      preLoaderRoute: typeof SourcingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapport': {
      id: '/rapport'
      path: '/rapport'
      fullPath: '/rapport'
      preLoaderRoute: typeof RapportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prospects': {
      id: '/prospects'
      path: '/prospects'
      fullPath: '/prospects'
      preLoaderRoute: typeof ProspectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partage': {
      id: '/partage'
      path: '/partage'
      fullPath: '/partage'
      preLoaderRoute: typeof PartageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facturation': {
      id: '/facturation'
      path: '/facturation'
      fullPath: '/facturation'
      preLoaderRoute: typeof FacturationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chasse': {
      id: '/chasse'
      path: '/chasse'
      fullPath: '/chasse'
      preLoaderRoute: typeof ChasseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyse': {
      id: '/analyse'
      path: '/analyse'
      fullPath: '/analyse'
      preLoaderRoute: typeof AnalyseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyseRoute: AnalyseRoute,
  ChasseRoute: ChasseRoute,
  FacturationRoute: FacturationRoute,
  PartageRoute: PartageRoute,
  PipelineRoute: PipelineRoute,
  ProspectsRoute: ProspectsRoute,
  RapportRoute: RapportRoute,
  SourcingRoute: SourcingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
