/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RapportRouteImport } from './routes/rapport'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as PartageRouteImport } from './routes/partage'
import { Route as ChasseRouteImport } from './routes/chasse'
import { Route as AnalyseRouteImport } from './routes/analyse'
import { Route as IndexRouteImport } from './routes/index'

const RapportRoute = RapportRouteImport.update({
  id: '/rapport',
  path: '/rapport',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const PartageRoute = PartageRouteImport.update({
  id: '/partage',
  path: '/partage',
  getParentRoute: () => rootRouteImport,
} as any)
const ChasseRoute = ChasseRouteImport.update({
  id: '/chasse',
  path: '/chasse',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyseRoute = AnalyseRouteImport.update({
  id: '/analyse',
  path: '/analyse',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyse': typeof AnalyseRoute
  '/chasse': typeof ChasseRoute
  '/partage': typeof PartageRoute
  '/pipeline': typeof PipelineRoute
  '/rapport': typeof RapportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyse': typeof AnalyseRoute
  '/chasse': typeof ChasseRoute
  '/partage': typeof PartageRoute
  '/pipeline': typeof PipelineRoute
  '/rapport': typeof RapportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyse': typeof AnalyseRoute
  '/chasse': typeof ChasseRoute
  '/partage': typeof PartageRoute
  '/pipeline': typeof PipelineRoute
  '/rapport': typeof RapportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/analyse' | '/chasse' | '/partage' | '/pipeline' | '/rapport'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/analyse' | '/chasse' | '/partage' | '/pipeline' | '/rapport'
  id:
    | '__root__'
    | '/'
    | '/analyse'
    | '/chasse'
    | '/partage'
    | '/pipeline'
    | '/rapport'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyseRoute: typeof AnalyseRoute
  ChasseRoute: typeof ChasseRoute
  PartageRoute: typeof PartageRoute
  PipelineRoute: typeof PipelineRoute
  RapportRoute: typeof RapportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rapport': {
      id: '/rapport'
      path: '/rapport'
      fullPath: '/rapport'
      preLoaderRoute: typeof RapportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partage': {
      id: '/partage'
      path: '/partage'
      fullPath: '/partage'
      preLoaderRoute: typeof PartageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chasse': {
      id: '/chasse'
      path: '/chasse'
      fullPath: '/chasse'
      preLoaderRoute: typeof ChasseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyse': {
      id: '/analyse'
      path: '/analyse'
      fullPath: '/analyse'
      preLoaderRoute: typeof AnalyseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyseRoute: AnalyseRoute,
  ChasseRoute: ChasseRoute,
  PartageRoute: PartageRoute,
  PipelineRoute: PipelineRoute,
  RapportRoute: RapportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
